matrix:
  include:
    - name: "Brownie Tests, Linting - Python 3.7 on Bionic Linux"
      script: tox -e lint,tests
    - name: "Stateful Tests - Python 3.7 on Bionic Linux"
      script: travis_wait tox -e stateful

dist: bionic
language: python
python: 3.7
install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python3.7-dev npm solc
  - npm -g install ganache-cli@6.8.2
  - python -m pip install tox==3.14.3
notifications:
  email: false